### PR TITLE
Add support for Django 4.0.x / Drop support for non-LTS versions of Django (1.11.x and 2.1.x)

### PR DESCRIPTION
**Pull request by ashtonpaul**
- `ugettext_lazy` is deprecated in Django 4.0. Updated references for `ugettext_lazy` to `gettext_lazy` to satisfy the deprecation warnings in 3.x and backwards incompatibility in 4.x.
- Updated travis.yml to include a missing dependency so tests in python 3.7.x can successfully complete (ref: https://travis-ci.community/t/build-errors-installing-a-common-dependency-docopt-on-python-3-7-but-not-other-versions/12886)
- Added missing test for unsupported image field
- Drop support for Django 1.11.x and Django 2.1.x

Fixes issue #26

### CODE REVIEW

**Comment by ArturoDucasse** [comment]
@mbourqui Can you approve this please.

**Comment by ashtonpaul** [comment]
@mbourqui When you get a chance can you review this please. Is anything missing that would prevent a new pypi version from being published? Let me know, thanks in advance.

**Comment by barseghyanartur** [comment]
@ashtonpaul 

It looks like this fork isn't maintained. Did you consider rebranding it and putting to PyPI under rebranded name?

**Comment by mbourqui** [comment]
Hi @ashtonpaul 

Really sorry for the long silence, I am pretty busy with other projects.

I really appreciate the time and effort you put into this PR. Please give me a few more days, I will review your PR over the weekend and release a new package on pypi next week.

Thanks for your contribution and comprehension

**Comment by mbourqui** [comment]
Good news, I released v5 to pypi! Thanks again for your contribution 💯 
Happy coding 🤓

**Comment by ashtonpaul** [comment]
@mbourqui No problem. Thanks for getting the changes pulled in. Glad I could help.

**Pull request merged**
